/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GameBet__factory } from "./GameBet__factory";
export { GameBetFactory__factory } from "./GameBetFactory__factory";
