/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameBet } from "./GameBet";
export type { GameBetFactory } from "./GameBetFactory";
export * as factories from "./factories";
export { GameBet__factory } from "./factories/GameBet__factory";
export { GameBetFactory__factory } from "./factories/GameBetFactory__factory";
